### ISSUE TITLE
2.0.1 fails to load in 1.16.5 but 2.0.0 does

### ISSUE THREAD

**Issue by oliver408i** [StealthyKamereon/passlock#6]
Following code is the error logs when enabling 2.0.1. 
`23.03 13:34:41 [Server] INFO [PassLock] Enabling PassLock v2.0.1
23.03 13:34:41 [Server] WARN [PassLock] Loaded class net.milkbowl.vault.economy.Economy from Vault v1.7.3-b131 which is not a depend, softdepend or loadbefore of this plugin.
23.03 13:34:41 [Server] ERROR Error occurred while enabling PassLock v2.0.1 (Is it up to date?)
23.03 13:34:41 [Server] INFO java.lang.NullPointerException: null
23.03 13:34:41 [Server] INFO at io.github.stealthykamereon.passlock.PassLock.generateFile(PassLock.java:87) ~[?:?]
23.03 13:34:41 [Server] INFO at io.github.stealthykamereon.passlock.PassLock.loadResources(PassLock.java:69) ~[?:?]
23.03 13:34:41 [Server] INFO at io.github.stealthykamereon.passlock.PassLock.onEnable(PassLock.java:44) ~[?:?]
23.03 13:34:41 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
23.03 13:34:41 [Server] INFO at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
23.03 13:34:41 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
23.03 13:34:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
23.03 13:34:41 [Server] INFO [PassLock] Disabling PassLock v2.0.1
23.03 13:34:41 [Server] ERROR Error occurred while disabling PassLock v2.0.1 (Is it up to date?)
23.03 13:34:41 [Server] INFO java.lang.NullPointerException: null
23.03 13:34:41 [Server] INFO at io.github.stealthykamereon.passlock.PassLock.onDisable(PassLock.java:110) ~[?:?]
23.03 13:34:41 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
23.03 13:34:41 [Server] INFO at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
23.03 13:34:41 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
23.03 13:34:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServer.java:769) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.handleCommandQueue(DedicatedServer.java:411) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:378) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-438]
23.03 13:34:41 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]`
2.0.0 works fine.

**Comment by StealthyKamereon** [comment]
Ok thanks, I'll work on it in an hour ;)

**Comment by StealthyKamereon** [comment]
It's fixed in the last version
