### ISSUE TITLE
put a temporary lock

### ISSUE THREAD

**Issue by cantorthiagofelipe** [StealthyKamereon/passlock#9]
When you enter the password, the doors are open forever, until someone clicks on them again. It would be useful to put a mode where the door is only open in X seconds (configurable by each lock)

**Comment by StealthyKamereon** [comment]
It's a good idea but what do you mean by each lock ?
The simplest thing I see is a custom time in the plugin config and then it's overwritten by by the user with a command.
But not for each lock

**Comment by StealthyKamereon** [comment]
Update to 2.2.0 to explore this new feature.
Only server-wise configuration is implemented for now, I'll add player-wise configuration later ;)

**Comment by cantorthiagofelipe** [comment]
> It's a good idea but what do you mean by each lock ? The simplest thing I see is a custom time in the plugin config and then it's overwritten by by the user with a command. But not for each lock

already added?
you are great, congrats...

for each port, I believe it's too much, the global configuration already solves this point

thanks for the help and the addition
